### ISSUE TITLE
"Helpful" error message also fails

### ISSUE THREAD

**Issue by KenXgh** [OnlineBuddies/Modyllic#311]
Hello Modyllic Team, I hope you are well.

If __modyllic-apply__ has to stop because of an error, it gives the command to run to skip that error and move on:

> To continue from after this statement, run:
> modyllic apply -d mysql:host=<hostname>;dbname=my_db;username=my_user;password=xxxxxx -s script.sql -k 8

This actually does not work and throw and error.

> Error: the script to apply is required
> Type "modyllic-apply --help" to get help.

I got around this by putting the dsn in double quotes.

> modyllic apply -d mysql:"host=<hostname>;dbname=my_db;username=my_user;password=xxxxxx" -s script.sql -k 8

I think the fix would be here.
> line 131 of __modyllic-apply__ echo "modyllic apply -d $dsntoapply -s $filename -k $stmt\n";

Can you fix this?

Thanks,
Ken

**Comment by aredridel** [comment]
Definitely! I can take a peek at it some time I hope, but if you want to hit the edit button on the file here in github, you can make the change and send a pull request!

**Comment by aredridel** [comment]
Alright. I think #312 should fix this.
