### ISSUE TITLE
How is Modyllic "user aware"?

### ISSUE THREAD

**Issue by KenXgh** [OnlineBuddies/Modyllic#314]
I generated "up" and "down" scripts with Modyllic in my home directory and then copied the entire release directory to /tmp and made it 777 so that a co-worker could run the scripts with applyAllDB but when he tried he got errors saying Modyllic was looking for log directories in my home directory.

Why wouldn't Modyllic just run the scripts? 

Thanks

**Comment by iarna** [comment]
The up and down scripts are just plain SQL. They have nothing user specific about them. (For example, the PaymentCore build process produces these scripts on the build server, and then during deploys they're run on entirely different machines by different users.)

I don't actually know why Modyllic would ever complain about "log directories" as it doesn't do logging. Without seeing the command and it's actual output I obviously can't offer suggestions...

Given what little you've said I'd jump to suggesting that the machine had some kind of php config error where the config pointed at your home directory. But that's still a wild-ass-guess .
